<?php

namespace App\Repository;

/**
 * IndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndicatorRepository extends \Doctrine\ORM\EntityRepository
{

}