<?php

namespace App\Repository;

/**
 * MedicalIndicatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicalIndicatorRepository extends \Doctrine\ORM\EntityRepository
{

}